Fix: deploy

diff --git a/.github/workflows/deplpoy.yml b/.github/workflows/deplpoy.yml
--- a/.github/workflows/deplpoy.yml
+++ b/.github/workflows/deplpoy.yml
@@ -27,7 +27,7 @@ jobs:
           SYNOLOGY_HOST: ${{ secrets.SYNOLOGY_HOST }}
         run: |
           # SSH 접속 및 Docker Compose 실행
-          sshpass -p ${{ secrets.SYNOLOGY_PASSWORD }} ssh -p ${{ secrets.SSH_PORT }} ${{ secrets.SYNOLOGY_USERNAME }}@${{ secrets.SYNOLOGY_HOST }} << 'EOF'
+          sshpass -p ${{ secrets.SYNOLOGY_PASSWORD }} ssh -p ${{ secrets.SSH_PORT }} ${{ secrets.SYNOLOGY_USERNAME }}@${{ secrets.SYNOLOGY_HOST }} 'bash -s' << 'EOF'
             # 1. Docker와 Docker Compose 설치 여부 확인 및 설치
             if ! command -v docker &> /dev/null
             then
@@ -45,11 +45,19 @@ jobs:
               sudo chmod +x /usr/local/bin/docker-compose
             fi
 
-            # 2. 작업 디렉토리 생성 및 이동
+            # 2. Git 설치 확인 및 설치
+            if ! command -v git &> /dev/null
+            then
+              echo "Git could not be found, installing..."
+              sudo apt-get update
+              sudo apt-get install -y git
+            fi
+
+            # 3. 작업 디렉토리 생성 및 이동
             mkdir -p ${{ secrets.DEPLOY_PATH }}
             cd ${{ secrets.DEPLOY_PATH }}
 
-            # 3. git clone 또는 pull
+            # 4. git clone 또는 pull
             if [ -d "my-react-nest-app" ]; then
               cd my-react-nest-app
               git pull origin main
@@ -58,7 +66,7 @@ jobs:
               cd my-react-nest-app
             fi
 
-            # 4. Docker Compose 실행
+            # 5. Docker Compose 실행
             if [ -f "docker-compose.yml" ]; then
               sudo docker-compose down
               sudo docker-compose up --build -d
