Fix: deploy

diff --git a/.github/workflows/deplpoy.yml b/.github/workflows/deplpoy.yml
--- a/.github/workflows/deplpoy.yml
+++ b/.github/workflows/deplpoy.yml
@@ -17,26 +17,30 @@ jobs:
         run: sudo apt-get install -y sshpass rsync
 
       - name: Set up SSH config
-
         run: |
           mkdir -p ~/.ssh
           echo -e "Host *\n  StrictHostKeyChecking no\n" > ~/.ssh/config
           ssh-keyscan -p ${{ secrets.SSH_PORT }} ${{ secrets.SYNOLOGY_HOST }} >> ~/.ssh/known_hosts
 
       - name: Deploy to Synology (using sshpass)
-        env:
-          SYNOLOGY_HOST: ${{ secrets.SYNOLOGY_HOST }}
-          SYNOLOGY_USERNAME: ${{ secrets.SYNOLOGY_USERNAME }}
-          SYNOLOGY_PASSWORD: ${{ secrets.SYNOLOGY_PASSWORD }}
-          SSH_PORT: ${{ secrets.SSH_PORT }}
-          DEPLOY_PATH: ${{ secrets.DEPLOY_PATH }}
         run: |
           # SSH 접속 및 Docker Compose 실행
           sshpass -p ${{ secrets.SYNOLOGY_PASSWORD }} ssh -p ${{ secrets.SSH_PORT }} ${{ secrets.SYNOLOGY_USERNAME }}@$SYNOLOGY_HOST << 'EOF'
-            # 폴더가 없으면 상위 폴더로 이동
-            cd $DEPLOY_PATH || cd $(dirname $DEPLOY_PATH) || exit 0  # 경로가 없으면 상위 폴더로 이동
+            # 1. git 설치 여부 확인 및 설치
+            if ! command -v git &> /dev/null
+            then
+                echo "git could not be found, installing..."
+                sudo apt-get update && sudo apt-get install -y git
+            fi
+
+            # 2. 폴더가 없으면 상위 폴더로 이동
+            cd ${{ secrets.DEPLOY_PATH }} || cd $(dirname ${{ secrets.DEPLOY_PATH }}) || exit 0
+
+            # 3. git pull 또는 git clone
             git pull origin main || git clone https://github.com/raincoat98/my-react-nest-app.git
             cd my-react-nest-app
-            sudo docker-compose down
-            sudo docker-compose up --build -d  # Docker Compose로 백그라운드에서 실행
+
+            # 4. Docker Compose 실행
+            sudo -S docker-compose down <<< ${{ secrets.SYNOLOGY_PASSWORD }}
+            sudo -S docker-compose up --build -d <<< ${{ secrets.SYNOLOGY_PASSWORD }}  # 비밀번호 자동 입력
           EOF
